### PR TITLE
implementation for DS2408

### PR DESCRIPTION
**Pull request by vytautassurvila**
Quite naive implementation for DS2408. This PR:
- fixes Read PIO Registers 0xF0 command. Previously it was pushing pin states as bytes instead of bits
- implements Channel-Access Write 0x5A command. Implementation ignores RSTZ as currently there is no possibility to set Control/Status register

The code was tested with following w1 masters:
- another Arduino running https://github.com/PaulStoffregen/OneWire
- BeagleBoneBlack running Linux 4.4.19. 1wire slave was accessed via original drivers: 
```
#set all pins to 1 (xFF)
echo -e '\xFF' |dd of=/sys/bus/w1/devices/29-010000000000/output bs=1 count=1 

#get values for all pins
dd if=/sys/bus/w1/devices/29-010000000000/state bs=1 count=1 | hexdump
```

All tests were run with original DS2408 hooked on same 1wire bus. It was used to compare commands and responses

### CODE REVIEW

**Comment by orgua** [comment]
Nice work and thanks for documenting it so well!

**Comment by orgua** [comment]
i tested your code with the ds9490 and found that the internal states of the outputs have the wrong start-configuration. getPinState() reads the 0x41 from the initialization of DS2408_PIO_LOGIC_REG but my masters says the ports are written like set in DS2408_PIO_OUTPUT_REG (all ON). Toggling them overwrites DS2408_PIO_LOGIC_REG completely. Maybe we should switch get/set to use DS2408_PIO_OUTPUT_REG?

**Comment by vytautassurvila** [comment]
Nice catch. I had some pins of original DS2408 pulled up and it was producing start configuration based on those. So I copied the register value to code but it totally slipped my mind that I should get initial values with all pins left floating.
Thanks for the library and keep up the good work!

**Comment by orgua** [comment]
once i had the datasheet open i extended the ds2408 a bit and made it work with my maxim-master. if you have time you could test the changes.

**Comment by vytautassurvila** [comment]
I tested your changes with another Arduino and BeagleBoneBlack - it works great. Thanks once again

**Pull request merged**
